# Generated by Django 6.0.5 on 2026-05-27 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.PositiveBigIntegerField(unique=True)),
                ('github_login', models.CharField(max_length=255)),
                ('html_url', models.URLField(blank=True)),
                ('access_token', models.TextField()),
                ('token_type', models.CharField(blank=True, max_length=50)),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
