# Generated by Django 6.0.5 on 2026-05-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_githubconnection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="githubconnection",
            options={
                "permissions": [
                    ("connect_github", "Puede conectar GitHub"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="summarytecnico",
            options={
                "permissions": [
                    ("generate_summary", "Puede generar summaries tecnicos"),
                    ("publish_summary_github", "Puede publicar summaries en GitHub"),
                ],
            },
        ),
    ]
