"""
Django settings for pr_summary_api project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3eqf9va@2fzhu9e@(h)#!^jckff26=@7dz1rnf1wmqz-lzi2eo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_spectacular',
    'django_filters',
    'rest_framework',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pr_summary_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pr_summary_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "api.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 10,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "API de Revisión Técnica de Pull Requests",
    "DESCRIPTION": (
        "API Django REST para autenticar usuarios con JWT, conectar una cuenta "
        "de GitHub por OAuth, consultar repositorios y pull requests, generar "
        "resúmenes técnicos con Gemini y publicar esos resúmenes en GitHub."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api/",
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
        "api.openapi.localize_redoc_schema",
    ],
    "ENUM_NAME_OVERRIDES": {
        "PullRequestEstadoEnum": "api.models.PullRequest.ESTADO_CHOICES",
        "SummaryTecnicoEstadoEnum": "api.models.SummaryTecnico.ESTADO_CHOICES",
        "GitHubPullRequestStateFilterEnum": ["open", "closed", "all"],
    },
    "SERVERS": [
        {
            "url": "http://127.0.0.1:8000",
            "description": "Servidor de desarrollo local",
        },
    ],
    "TAGS": [
        {
            "name": "Autenticación",
            "description": (
                "Endpoints para obtener y renovar tokens JWT. Usá el token `access` "
                "en el header `Authorization: Bearer <access_token>` para consumir "
                "los endpoints protegidos."
            ),
        },
        {
            "name": "GitHub OAuth",
            "description": (
                "Flujo de autorización para vincular una cuenta de GitHub con la API. "
                "La conexión resultante se guarda localmente y queda disponible para "
                "consultar repositorios y pull requests."
            ),
        },
        {
            "name": "GitHub Repositorios",
            "description": (
                "Consulta repositorios remotos visibles para la cuenta de GitHub conectada. "
                "Estos endpoints leen datos desde GitHub y los comparan con los repositorios "
                "guardados localmente."
            ),
        },
        {
            "name": "GitHub Pull Requests",
            "description": (
                "Consulta pull requests remotos, detalle técnico, archivos, commits, "
                "comentarios, reviews, diff y generación de resúmenes técnicos con IA."
            ),
        },
        {
            "name": "Conexiones GitHub locales",
            "description": (
                "Credenciales OAuth guardadas por la API para consultar GitHub. En uso normal "
                "se crean desde el flujo OAuth y no manualmente."
            ),
        },
        {
            "name": "Repositorios locales",
            "description": (
                "Repositorios de GitHub registrados en la base local para seguimiento y "
                "relación con pull requests y resúmenes."
            ),
        },
        {
            "name": "Pull Requests locales",
            "description": (
                "Pull requests guardados localmente como referencia interna. No reemplazan "
                "ni modifican el pull request remoto en GitHub."
            ),
        },
        {
            "name": "Resúmenes técnicos locales",
            "description": (
                "Historial local de resúmenes técnicos generados para pull requests. La "
                "generación con IA se realiza desde el endpoint remoto de resumen."
            ),
        },
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
}

GITHUB_CLIENT_ID = os.environ.get("GITHUB_CLIENT_ID", "")
GITHUB_CLIENT_SECRET = os.environ.get("GITHUB_CLIENT_SECRET", "")
GITHUB_CALLBACK_URL = os.environ.get(
    "GITHUB_CALLBACK_URL",
    "http://127.0.0.1:8000/api/github/oauth/callback/",
)
